name: Nim

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:0.16.0

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: nimble test
